-- Invoice templates
CREATE TABLE IF NOT EXISTS `invoice_templates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `html` mediumtext NOT NULL,
  `is_default` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invoice_templates_name` (`name`),
  KEY `idx_invoice_templates_default` (`is_default`)
);

-- Parties (suppliers and clients)
CREATE TABLE IF NOT EXISTS `parties` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `role` varchar(16) NOT NULL,
  `name` varchar(255) NOT NULL,
  `tax_id` varchar(64) DEFAULT NULL,
  `vat_id` varchar(64) DEFAULT NULL,
  `address_line1` varchar(255) NOT NULL,
  `address_line2` varchar(255) DEFAULT NULL,
  `city` varchar(128) NOT NULL,
  `region` varchar(128) DEFAULT NULL,
  `postal_code` varchar(32) DEFAULT NULL,
  `country` varchar(128) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(64) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `locale_code` varchar(8) DEFAULT NULL,
  `locale_language` varchar(8) DEFAULT NULL,
  `locale_country` varchar(8) DEFAULT NULL,
  `date_pattern` varchar(32) DEFAULT NULL,
  `invoice_start_number` bigint unsigned DEFAULT NULL,
  `invoice_prefix` varchar(16) DEFAULT NULL,
  `invoice_number_digits` int unsigned DEFAULT NULL,
  `last_invoice_number` bigint unsigned DEFAULT NULL,
  `default_template_id` bigint unsigned DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `currency_code` varchar(3) DEFAULT NULL,
  `default_tax_rate` decimal(5,4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_parties_role_tax_id` (`role`,`tax_id`),
  KEY `idx_parties_role_vat_id` (`role`,`vat_id`),
  KEY `idx_parties_default_template_id` (`default_template_id`),
  CONSTRAINT `fk_parties_default_template` FOREIGN KEY (`default_template_id`) REFERENCES `invoice_templates` (`id`)
);

-- Invoices
CREATE TABLE IF NOT EXISTS `invoices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `template_id` bigint unsigned DEFAULT NULL,
  `supplier_party_id` bigint unsigned DEFAULT NULL,
  `client_party_id` bigint unsigned DEFAULT NULL,
  `invoice_number` varchar(64) NOT NULL,
  `invoice_number_int` bigint unsigned NOT NULL,
  `issue_date` date NOT NULL,
  `due_date` date DEFAULT NULL,
  `locale_code` varchar(8) NOT NULL,
  `currency_code` char(3) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'issued',
  `supplier_name` varchar(255) NOT NULL,
  `supplier_tax_id` varchar(64) DEFAULT NULL,
  `supplier_vat_id` varchar(64) DEFAULT NULL,
  `supplier_address_line1` varchar(255) NOT NULL,
  `supplier_address_line2` varchar(255) DEFAULT NULL,
  `supplier_city` varchar(128) NOT NULL,
  `supplier_region` varchar(128) DEFAULT NULL,
  `supplier_postal_code` varchar(32) DEFAULT NULL,
  `supplier_country` varchar(128) NOT NULL,
  `supplier_email` varchar(255) DEFAULT NULL,
  `supplier_phone` varchar(64) DEFAULT NULL,
  `client_name` varchar(255) NOT NULL,
  `client_tax_id` varchar(64) DEFAULT NULL,
  `client_vat_id` varchar(64) DEFAULT NULL,
  `client_address_line1` varchar(255) NOT NULL,
  `client_address_line2` varchar(255) DEFAULT NULL,
  `client_city` varchar(128) NOT NULL,
  `client_region` varchar(128) DEFAULT NULL,
  `client_postal_code` varchar(32) DEFAULT NULL,
  `client_country` varchar(128) NOT NULL,
  `client_email` varchar(255) DEFAULT NULL,
  `client_phone` varchar(64) DEFAULT NULL,
  `subtotal` decimal(14,2) NOT NULL DEFAULT '0.00',
  `tax_total` decimal(14,2) NOT NULL DEFAULT '0.00',
  `total` decimal(14,2) NOT NULL DEFAULT '0.00',
  `notes` text,
  `invoice_html` mediumtext,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_invoices_supplier_number` (`supplier_party_id`,`invoice_number`),
  KEY `idx_invoices_template_id` (`template_id`),
  KEY `idx_invoices_supplier_party_id` (`supplier_party_id`),
  KEY `idx_invoices_client_party_id` (`client_party_id`),
  KEY `idx_invoices_issue_date` (`issue_date`),
  CONSTRAINT `fk_invoices_client_party_id` FOREIGN KEY (`client_party_id`) REFERENCES `parties` (`id`),
  CONSTRAINT `fk_invoices_supplier_party_id` FOREIGN KEY (`supplier_party_id`) REFERENCES `parties` (`id`),
  CONSTRAINT `fk_invoices_template_id` FOREIGN KEY (`template_id`) REFERENCES `invoice_templates` (`id`)
);

-- Invoice line items
CREATE TABLE IF NOT EXISTS `invoice_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `invoice_id` bigint unsigned NOT NULL,
  `line_number` int unsigned NOT NULL,
  `description` varchar(512) NOT NULL,
  `quantity` decimal(12,3) NOT NULL DEFAULT '1.000',
  `unit_price` decimal(14,2) NOT NULL,
  `discount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `tax_rate` decimal(5,2) NOT NULL DEFAULT '0.00',
  `line_subtotal` decimal(14,2) NOT NULL,
  `line_tax` decimal(14,2) NOT NULL,
  `line_total` decimal(14,2) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invoice_items_invoice_line` (`invoice_id`,`line_number`),
  KEY `idx_invoice_items_invoice_id` (`invoice_id`),
  CONSTRAINT `fk_invoice_items_invoice_id` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`)
);
