#!/bin/bash
set -euo pipefail

# Slam the API with concurrent invoice generation requests
# Usage: ./gen-test.sh [SUPPLIER_ID] [COUNT] [BASE_URL] [API_KEY]
#   or:  API_KEY=your_key ./gen-test.sh [SUPPLIER_ID] [COUNT] [BASE_URL]

SUPPLIER_ID="${1:-1}"
COUNT="${2:-20}"
BASE_URL="${3:-http://localhost:8080}"
API_KEY="${4:-${API_KEY:-}}"

if [[ -z "$API_KEY" ]]; then
    echo "Error: API_KEY is required"
    echo "Usage: API_KEY=your_key ./gen-test.sh [SUPPLIER_ID] [COUNT] [BASE_URL]"
    echo "   or: ./gen-test.sh [SUPPLIER_ID] [COUNT] [BASE_URL] [API_KEY]"
    exit 1
fi

echo "Slamming API with ${COUNT} concurrent invoice requests"
echo "Supplier ID: ${SUPPLIER_ID}"
echo "Base URL: ${BASE_URL}"
echo "API Key: ${API_KEY:0:8}..." # Show only first 8 chars
echo "---"

function generateInvoice {
    local i=$1
    local clientName="Load Test Client ${i}"

    curl -s -X POST "${BASE_URL}/api/v1/invoices/generate" \
        -H "Authorization: Bearer ${API_KEY}" \
        -H "Content-Type: application/json" \
        -d "{
            \"supplierId\": ${SUPPLIER_ID},
            \"client\": {
                \"name\": \"${clientName}\",
                \"addressLine1\": \"${i} Test Street\",
                \"city\": \"TestCity\",
                \"country\": \"Testland\"
            },
            \"items\": [
                {
                    \"description\": \"Load test item ${i}\",
                    \"quantity\": ${i},
                    \"unitPrice\": $((RANDOM % 500 + 10)).00
                }
            ],
            \"notes\": \"Generated by slam-invoices.sh\"
        }" && echo " [${i}] OK" || echo " [${i}] FAILED"
}

# fire all requests (semi-)concurrently
for i in $(seq 1 "${COUNT}"); do
    generateInvoice "${i}" &
done

# wait for all background jobs
wait

echo "---"
echo "Done. Sent ${COUNT} requests."
